# Generated by Django 2.1.5 on 2022-03-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('picture', models.TextField(max_length=512, null=True)),
                ('location', models.CharField(max_length=64, null=True)),
                ('description', models.CharField(max_length=64, null=True)),
                ('book_ticket', models.CharField(max_length=64, null=True)),
                ('review', models.CharField(max_length=64, null=True)),
                ('visit', models.IntegerField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
